package:
  name: wquantiles
  version: "0.3"

source:
  fn: wquantiles-0.3.tar.gz
  url: https://files.pythonhosted.org/packages/81/62/2253d971af300f21355858f6bafacbcc054c0b0a946acd653da2740c443a/wquantiles-0.3.tar.gz
  md5: 1281ea42e07e586120b230f505874a99
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # noarch_python: True
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - wquantiles = wquantiles:main
    #
    # Would create an entry point called wquantiles that calls wquantiles.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - numpy

  run:
    - python
    - numpy

# test:
  # Python imports
  # imports:

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://github.com/nudomarinero/wquantiles/
  license: MIT License
  summary: 'Weighted quantiles, including weighted median, based on numpy'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
